# Generated by Django 2.1 on 2018-10-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banktransfer_custom', '0004_auto_20170619_1125'),
    ]

    operations = []
