# Generated by Django 5.2.17 on 2026-09-02 03:26

import django.db.models.deletion
import pretix_banktransfer_custom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banktransfer_custom", "0012_org_level_plugin"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=pretix_banktransfer_custom.models.paymentproof_name,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banktransfer_custom_proof",
                        to="pretixbase.orderpayment",
                    ),
                ),
            ],
            options={
                "ordering": ("-uploaded",),
            },
        ),
    ]
